//CONSTANTES DE ESTADO DEL REPORTE PARA EL USUARIO
export const EN_PROCESO = "EN PROCESO";
export const SOLUCIONADO = "SOLUCIONADO";




//CONSTANTES DE ACTIVIDAD DE USUARIO
export const ACTIVO = "ACTIVO";
export const INACTIVO = "INACTIVO"
export const SUSPENDIDO = "SUSPENDIDO"


//CONSTANTES DE ROLES
export const ADMINISTRADOR = "1"
export const EMPRESA = "2"
export const OPERADOR = "3"
export const USUARIO_CONSUMIDOR = "4"


//RETORALIMENTACION DE SOLUCIONES DE REPORTE
export const SIN_REVISION="Sin revision"
export const INFRAESTRUCTURA_DOMICILIO="Infraestructura domicilio"
export const INFRAESTRUCTURA_EXTERIOR="Infraestructura exterior"
export const INFRAESTRUCTURA_INTERIOR="Infraestructura interior"
export const CONTADOR_DOMICILIO="Contador Cliente"
export const MANTENIMIENTO_DOMICILIO="Mantenimiento para cliente"
export const MANTENIMIENTO_EXTERIOR="Mantenimiento para exteriores"
export const MANTENIMIENTO_INTERIOR="Mantenimiento para empresa"
export const OTRO_ASUNTO="Otro analisis"

export const ARREGLO_CONSTANTES = [
  SIN_REVISION,
  INFRAESTRUCTURA_DOMICILIO,
  INFRAESTRUCTURA_EXTERIOR,
  INFRAESTRUCTURA_INTERIOR,
  CONTADOR_DOMICILIO,
  MANTENIMIENTO_DOMICILIO,
  MANTENIMIENTO_EXTERIOR,
  MANTENIMIENTO_INTERIOR,
  OTRO_ASUNTO
];


//RETROALIMENTACION DE SOLUCIONES DE REPORTE ABREVIADAS
export const SIN_REVISION_A="SR"
export const INFRAESTRUCTURA_DOMICILIO_A="ID"
export const INFRAESTRUCTURA_EXTERIOR_A="IE"
export const INFRAESTRUCTURA_INTERIOR_A="II"
export const CONTADOR_DOMICILIO_A="CC"
export const MANTENIMIENTO_DOMICILIO_A="MC"
export const MANTENIMIENTO_EXTERIOR_A="ME"
export const MANTENIMIENTO_INTERIOR_A="MI"
export const OTRO_ASUNTO_A="OA"

export const ARREGLO_CONSTANTES_ABREVIADO = [
  SIN_REVISION_A,
  INFRAESTRUCTURA_DOMICILIO_A,
  INFRAESTRUCTURA_EXTERIOR_A,
  INFRAESTRUCTURA_INTERIOR_A,
  CONTADOR_DOMICILIO_A,
  MANTENIMIENTO_DOMICILIO_A,
  MANTENIMIENTO_EXTERIOR_A,
  MANTENIMIENTO_INTERIOR_A,
  OTRO_ASUNTO_A
];
